// Generated by: DeepSeek R1 2025.6.5
// 原本版本存在问题，此版本为修补，不一定能AC
#include <iostream>
#include <stack>
#include <sstream>
#include <cctype>
#include <string>
using namespace std;

int main() {
    string s;
    getline(cin, s);
    stack<char> opStack;
    ostringstream oss;
    string currentNumber;

    auto getPriority = [](char op) {
        if (op == '+' || op == '-') return 1;
        if (op == '*' || op == '/') return 2;
        return 0;
    };

    for (char c : s) {
        if (c == ' ') continue;

        if (isdigit(c)) {
            currentNumber += c;
        } else {
            if (!currentNumber.empty()) {
                if (oss.str().empty()) oss << currentNumber;
                else oss << ' ' << currentNumber;
                currentNumber = "";
            }

            if (c == '(') {
                opStack.push(c);
            } else if (c == ')') {
                while (!opStack.empty() && opStack.top() != '(') {
                    oss << ' ' << opStack.top();
                    opStack.pop();
                }
                if (!opStack.empty() && opStack.top() == '(') {
                    opStack.pop();
                }
            } else {
                while (!opStack.empty() && opStack.top() != '(' && getPriority(opStack.top()) >= getPriority(c)) {
                    oss << ' ' << opStack.top();
                    opStack.pop();
                }
                opStack.push(c);
            }
        }
    }

    if (!currentNumber.empty()) {
        if (oss.str().empty()) oss << currentNumber;
        else oss << ' ' << currentNumber;
    }

    while (!opStack.empty()) {
        oss << ' ' << opStack.top();
        opStack.pop();
    }

    cout << oss.str();
    return 0;
}